apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: work-report-hpa
  namespace: work-report
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: work-report-app
  minReplicas: 3
  maxReplicas: 20
  metrics:
    # 1. CPU-based Auto Scaling (Saat banyak request atau query berat)
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    # 2. Memory-based Auto Scaling
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
        - type: Pods
          value: 4
          periodSeconds: 15
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300 # Mencegah flapping saat lonjakan traffic turun
      policies:
        - type: Percent
          value: 20
          periodSeconds: 60
